// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Artigo", b =>
                {
                    b.Property<string>("ArtigoCodigo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("artigocodigo");

                    b.Property<string>("Categoria")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("integer")
                        .HasColumnName("familiaid");

                    b.Property<string>("MaquinaCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("maquinacodigo");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric")
                        .HasColumnName("peso");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unidade");

                    b.HasKey("ArtigoCodigo")
                        .HasName("pk_artigos");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("ix_artigos_familiaid");

                    b.HasIndex("MaquinaCodigo")
                        .HasDatabaseName("ix_artigos_maquinacodigo");

                    b.ToTable("artigos", (string)null);
                });

            modelBuilder.Entity("backend.Models.ArtigoCusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtigoCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("artigocodigo");

                    b.Property<decimal>("CustoPintura")
                        .HasColumnType("numeric")
                        .HasColumnName("custopintura");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datafim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datainicio");

                    b.Property<decimal>("PraMatprim")
                        .HasColumnType("numeric")
                        .HasColumnName("pramatprim");

                    b.Property<decimal>("PrecoEnergia")
                        .HasColumnType("numeric")
                        .HasColumnName("precoenergia");

                    b.Property<decimal>("PriTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("pritotal");

                    b.Property<decimal>("PruMaquina")
                        .HasColumnType("numeric")
                        .HasColumnName("prumaquina");

                    b.Property<decimal>("PrwiMaoobra")
                        .HasColumnType("numeric")
                        .HasColumnName("prwimaoobra");

                    b.HasKey("Id")
                        .HasName("pk_artigoscusto");

                    b.HasIndex("ArtigoCodigo")
                        .HasDatabaseName("ix_artigoscusto_artigocodigo");

                    b.ToTable("artigoscusto", (string)null);
                });

            modelBuilder.Entity("backend.Models.AssinaturaDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssinaturaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("assinaturahash");

                    b.Property<DateTime>("DataAssinatura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataassinatura");

                    b.Property<string>("DepartamentoAssinatura")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("departamentoassinatura");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("integer")
                        .HasColumnName("documentoid");

                    b.Property<string>("UtilizadorCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("utilizadorcodigo");

                    b.HasKey("Id")
                        .HasName("pk_assinaturasdocumento");

                    b.HasIndex("AssinaturaHash")
                        .IsUnique()
                        .HasDatabaseName("ix_assinaturasdocumento_assinaturahash");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("ix_assinaturasdocumento_documentoid");

                    b.HasIndex("UtilizadorCodigo")
                        .HasDatabaseName("ix_assinaturasdocumento_utilizadorcodigo");

                    b.ToTable("assinaturasdocumento", (string)null);
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_cargos");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("ix_cargos_descricao");

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("backend.Models.CatalogoDefeito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_catalogosdefeito");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_catalogosdefeito_codigo");

                    b.ToTable("catalogosdefeito", (string)null);
                });

            modelBuilder.Entity("backend.Models.Diversos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtigoCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("artigocodigo");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("integer")
                        .HasColumnName("familiaid");

                    b.Property<string>("Propriedade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("propriedade");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_diversoslista");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("ix_diversoslista_familiaid");

                    b.HasIndex("ArtigoCodigo", "Propriedade")
                        .IsUnique()
                        .HasDatabaseName("ix_diversoslista_artigocodigo_propriedade");

                    b.ToTable("diversoslista", (string)null);
                });

            modelBuilder.Entity("backend.Models.DocumentoTecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtigoCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("artigocodigo");

                    b.Property<string>("CaminhoFicheiro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caminhoficheiro");

                    b.Property<bool>("IsOficial")
                        .HasColumnType("boolean")
                        .HasColumnName("isoficial");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tipodocumento");

                    b.HasKey("Id")
                        .HasName("pk_documentostecnicos");

                    b.HasIndex("ArtigoCodigo")
                        .HasDatabaseName("ix_documentostecnicos_artigocodigo");

                    b.HasIndex("CaminhoFicheiro")
                        .IsUnique()
                        .HasDatabaseName("ix_documentostecnicos_caminhoficheiro");

                    b.ToTable("documentostecnicos", (string)null);
                });

            modelBuilder.Entity("backend.Models.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("ParametrosInspecao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("parametrosinspecao");

                    b.HasKey("Id")
                        .HasName("pk_familias");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_familias_codigo");

                    b.ToTable("familias", (string)null);
                });

            modelBuilder.Entity("backend.Models.Fornecedor", b =>
                {
                    b.Property<string>("FornecedorCodigo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fornecedorcodigo");

                    b.Property<string>("Morada")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("morada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.HasKey("FornecedorCodigo")
                        .HasName("pk_fornecedores");

                    b.ToTable("fornecedores", (string)null);
                });

            modelBuilder.Entity("backend.Models.FornecedorClassificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoFiscal")
                        .HasColumnType("integer")
                        .HasColumnName("anofiscal");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("classificacao");

                    b.Property<string>("FornecedorCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fornecedorcodigo");

                    b.HasKey("Id")
                        .HasName("pk_fornecedoresclassificacao");

                    b.HasIndex("FornecedorCodigo", "AnoFiscal")
                        .IsUnique()
                        .HasDatabaseName("ix_fornecedoresclassificacao_fornecedorcodigo_anofiscal");

                    b.ToTable("fornecedoresclassificacao", (string)null);
                });

            modelBuilder.Entity("backend.Models.JustificacaoNOK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefeitoId")
                        .HasColumnType("integer")
                        .HasColumnName("defeitoid");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacoes");

                    b.Property<decimal>("QtdAfetada")
                        .HasColumnType("numeric")
                        .HasColumnName("qtdafetada");

                    b.Property<int>("RececaoId")
                        .HasColumnType("integer")
                        .HasColumnName("rececaoid");

                    b.HasKey("Id")
                        .HasName("pk_justificacoesnok");

                    b.HasIndex("DefeitoId")
                        .HasDatabaseName("ix_justificacoesnok_defeitoid");

                    b.HasIndex("RececaoId")
                        .HasDatabaseName("ix_justificacoesnok_rececaoid");

                    b.ToTable("justificacoesnok", (string)null);
                });

            modelBuilder.Entity("backend.Models.Maquina", b =>
                {
                    b.Property<string>("MaquinaCodigo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("maquinacodigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<decimal>("PrecoEnergia")
                        .HasColumnType("numeric")
                        .HasColumnName("precoenergia");

                    b.Property<decimal>("PrecoMaoObra")
                        .HasColumnType("numeric")
                        .HasColumnName("precomaoobra");

                    b.Property<decimal>("PrecoUsinagem")
                        .HasColumnType("numeric")
                        .HasColumnName("precousinagem");

                    b.Property<int?>("Setor")
                        .HasColumnType("integer")
                        .HasColumnName("setor");

                    b.HasKey("MaquinaCodigo")
                        .HasName("pk_maquinas");

                    b.ToTable("maquinas", (string)null);
                });

            modelBuilder.Entity("backend.Models.Movimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtigoCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("artigocodigo");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datamovimento");

                    b.Property<int?>("DefeitoId")
                        .HasColumnType("integer")
                        .HasColumnName("defeitoid");

                    b.Property<bool>("Descontar")
                        .HasColumnType("boolean")
                        .HasColumnName("descontar");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("estado");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("localizacao");

                    b.Property<string>("MaquinaCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("maquinacodigo");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacoes");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<int?>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("servicoid");

                    b.Property<int>("TipoMovimentoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipomovimentoid");

                    b.Property<string>("UtilizadorCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("utilizadorcodigo");

                    b.HasKey("Id")
                        .HasName("pk_movimentos");

                    b.HasIndex("ArtigoCodigo")
                        .HasDatabaseName("ix_movimentos_artigocodigo");

                    b.HasIndex("DefeitoId")
                        .HasDatabaseName("ix_movimentos_defeitoid");

                    b.HasIndex("MaquinaCodigo")
                        .HasDatabaseName("ix_movimentos_maquinacodigo");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("ix_movimentos_servicoid");

                    b.HasIndex("TipoMovimentoId")
                        .HasDatabaseName("ix_movimentos_tipomovimentoid");

                    b.HasIndex("UtilizadorCodigo")
                        .HasDatabaseName("ix_movimentos_utilizadorcodigo");

                    b.ToTable("movimentos", (string)null);
                });

            modelBuilder.Entity("backend.Models.NaoConforme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataregisto");

                    b.Property<int>("IdMovimento")
                        .HasColumnType("integer")
                        .HasColumnName("idmovimento");

                    b.Property<decimal>("QtdSage")
                        .HasColumnType("numeric")
                        .HasColumnName("qtdsage");

                    b.HasKey("Id")
                        .HasName("pk_naoconformes");

                    b.HasIndex("IdMovimento")
                        .IsUnique()
                        .HasDatabaseName("ix_naoconformes_idmovimento");

                    b.ToTable("naoconformes", (string)null);
                });

            modelBuilder.Entity("backend.Models.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_niveis");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("ix_niveis_descricao");

                    b.ToTable("niveis", (string)null);
                });

            modelBuilder.Entity("backend.Models.RececaoInspecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtigoCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("artigocodigo");

                    b.Property<decimal>("CustoUnitarioMomento")
                        .HasColumnType("numeric")
                        .HasColumnName("custounitariomomento");

                    b.Property<DateTime>("DataRececao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datarececao");

                    b.Property<string>("DecisaoFinal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("decisaofinal");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Fatura")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fatura");

                    b.Property<string>("FornecedorCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fornecedorcodigo");

                    b.Property<int>("Linha")
                        .HasColumnType("integer")
                        .HasColumnName("linha");

                    b.Property<decimal>("QtdTotalRecebida")
                        .HasColumnType("numeric")
                        .HasColumnName("qtdtotalrecebida");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<string>("SagePedidoId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sagepedidoid");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unidade");

                    b.Property<string>("UtilizadorCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("utilizadorcodigo");

                    b.HasKey("Id")
                        .HasName("pk_rececoesinspecao");

                    b.HasIndex("ArtigoCodigo")
                        .HasDatabaseName("ix_rececoesinspecao_artigocodigo");

                    b.HasIndex("FornecedorCodigo")
                        .HasDatabaseName("ix_rececoesinspecao_fornecedorcodigo");

                    b.HasIndex("UtilizadorCodigo")
                        .HasDatabaseName("ix_rececoesinspecao_utilizadorcodigo");

                    b.HasIndex("SagePedidoId", "Linha")
                        .IsUnique()
                        .HasDatabaseName("ix_rececoesinspecao_sagepedidoid_linha");

                    b.ToTable("rececoesinspecao", (string)null);
                });

            modelBuilder.Entity("backend.Models.Retrabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcaoExecutar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("acaoexecutar");

                    b.Property<decimal?>("CustoNc")
                        .HasColumnType("numeric")
                        .HasColumnName("custonc");

                    b.Property<decimal?>("CustoRejeicao")
                        .HasColumnType("numeric")
                        .HasColumnName("custorejeicao");

                    b.Property<decimal?>("CustoRetrabalho")
                        .HasColumnType("numeric")
                        .HasColumnName("custoretrabalho");

                    b.Property<DateTime>("DataRetrabalho")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataretrabalho");

                    b.Property<int>("IdMovimento")
                        .HasColumnType("integer")
                        .HasColumnName("idmovimento");

                    b.Property<string>("MaquinaRejeicao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("maquinarejeicao");

                    b.Property<string>("SetorIdentificado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("setoridentificado");

                    b.Property<decimal>("TempoMinutos")
                        .HasColumnType("numeric")
                        .HasColumnName("tempominutos");

                    b.HasKey("Id")
                        .HasName("pk_retrabalhos");

                    b.HasIndex("IdMovimento")
                        .IsUnique()
                        .HasDatabaseName("ix_retrabalhos_idmovimento");

                    b.HasIndex("MaquinaRejeicao")
                        .HasDatabaseName("ix_retrabalhos_maquinarejeicao");

                    b.ToTable("retrabalhos", (string)null);
                });

            modelBuilder.Entity("backend.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CustoDecapar")
                        .HasColumnType("numeric")
                        .HasColumnName("custodecapar");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datafim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datainicio");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_servicos");

                    b.ToTable("servicos", (string)null);
                });

            modelBuilder.Entity("backend.Models.TipoMovimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_tiposmovimento");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("ix_tiposmovimento_descricao");

                    b.ToTable("tiposmovimento", (string)null);
                });

            modelBuilder.Entity("backend.Models.Utilizador", b =>
                {
                    b.Property<string>("UtilizadorCodigo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("utilizadorcodigo");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("CargoId")
                        .HasColumnType("integer")
                        .HasColumnName("cargoid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer")
                        .HasColumnName("nivelid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.HasKey("UtilizadorCodigo")
                        .HasName("pk_utilizadores");

                    b.HasIndex("CargoId")
                        .HasDatabaseName("ix_utilizadores_cargoid");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_utilizadores_email");

                    b.HasIndex("NivelId")
                        .HasDatabaseName("ix_utilizadores_nivelid");

                    b.ToTable("utilizadores", (string)null);
                });

            modelBuilder.Entity("backend.Models.Artigo", b =>
                {
                    b.HasOne("backend.Models.Familia", "Familia")
                        .WithMany()
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artigos_familias_familiaid");

                    b.HasOne("backend.Models.Maquina", "Maquina")
                        .WithMany("Artigos")
                        .HasForeignKey("MaquinaCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artigos_maquinas_maquinacodigo");

                    b.Navigation("Familia");

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("backend.Models.ArtigoCusto", b =>
                {
                    b.HasOne("backend.Models.Artigo", "Artigo")
                        .WithMany("HistoricoCustos")
                        .HasForeignKey("ArtigoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artigoscusto_artigos_artigocodigo");

                    b.Navigation("Artigo");
                });

            modelBuilder.Entity("backend.Models.AssinaturaDocumento", b =>
                {
                    b.HasOne("backend.Models.DocumentoTecnico", "Documento")
                        .WithMany("Assinaturas")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assinaturasdocumento_documentostecnicos_documentoid");

                    b.HasOne("backend.Models.Utilizador", "Utilizador")
                        .WithMany("Assinaturas")
                        .HasForeignKey("UtilizadorCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assinaturasdocumento_utilizadores_utilizadorcodigo");

                    b.Navigation("Documento");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("backend.Models.Diversos", b =>
                {
                    b.HasOne("backend.Models.Artigo", "Artigo")
                        .WithMany("PropriedadesPDM")
                        .HasForeignKey("ArtigoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diversoslista_artigos_artigocodigo");

                    b.HasOne("backend.Models.Familia", null)
                        .WithMany("DiversosLista")
                        .HasForeignKey("FamiliaId")
                        .HasConstraintName("fk_diversoslista_familias_familiaid");

                    b.Navigation("Artigo");
                });

            modelBuilder.Entity("backend.Models.DocumentoTecnico", b =>
                {
                    b.HasOne("backend.Models.Artigo", "Artigo")
                        .WithMany("Documentos")
                        .HasForeignKey("ArtigoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documentostecnicos_artigos_artigocodigo");

                    b.Navigation("Artigo");
                });

            modelBuilder.Entity("backend.Models.FornecedorClassificacao", b =>
                {
                    b.HasOne("backend.Models.Fornecedor", "Fornecedor")
                        .WithMany("Classificacoes")
                        .HasForeignKey("FornecedorCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fornecedoresclassificacao_fornecedores_fornecedorcodigo");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("backend.Models.JustificacaoNOK", b =>
                {
                    b.HasOne("backend.Models.CatalogoDefeito", "Defeito")
                        .WithMany()
                        .HasForeignKey("DefeitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_justificacoesnok_catalogosdefeito_defeitoid");

                    b.HasOne("backend.Models.RececaoInspecao", "Rececao")
                        .WithMany("Justificacoes")
                        .HasForeignKey("RececaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_justificacoesnok_rececoesinspecao_rececaoid");

                    b.Navigation("Defeito");

                    b.Navigation("Rececao");
                });

            modelBuilder.Entity("backend.Models.Movimento", b =>
                {
                    b.HasOne("backend.Models.Artigo", "Artigo")
                        .WithMany()
                        .HasForeignKey("ArtigoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentos_artigos_artigocodigo");

                    b.HasOne("backend.Models.CatalogoDefeito", "Defeito")
                        .WithMany()
                        .HasForeignKey("DefeitoId")
                        .HasConstraintName("fk_movimentos_catalogosdefeito_defeitoid");

                    b.HasOne("backend.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentos_maquinas_maquinacodigo");

                    b.HasOne("backend.Models.Servico", "Servico")
                        .WithMany("Movimentos")
                        .HasForeignKey("ServicoId")
                        .HasConstraintName("fk_movimentos_servicos_servicoid");

                    b.HasOne("backend.Models.TipoMovimento", "Tipo")
                        .WithMany("Movimentos")
                        .HasForeignKey("TipoMovimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentos_tiposmovimento_tipomovimentoid");

                    b.HasOne("backend.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentos_utilizadores_utilizadorcodigo");

                    b.Navigation("Artigo");

                    b.Navigation("Defeito");

                    b.Navigation("Maquina");

                    b.Navigation("Servico");

                    b.Navigation("Tipo");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("backend.Models.NaoConforme", b =>
                {
                    b.HasOne("backend.Models.Movimento", "Movimento")
                        .WithOne("NaoConforme")
                        .HasForeignKey("backend.Models.NaoConforme", "IdMovimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_naoconformes_movimentos_idmovimento");

                    b.Navigation("Movimento");
                });

            modelBuilder.Entity("backend.Models.RececaoInspecao", b =>
                {
                    b.HasOne("backend.Models.Artigo", "Artigo")
                        .WithMany("Rececoes")
                        .HasForeignKey("ArtigoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rececoesinspecao_artigos_artigocodigo");

                    b.HasOne("backend.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rececoesinspecao_fornecedores_fornecedorcodigo");

                    b.HasOne("backend.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rececoesinspecao_utilizadores_utilizadorcodigo");

                    b.Navigation("Artigo");

                    b.Navigation("Fornecedor");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("backend.Models.Retrabalho", b =>
                {
                    b.HasOne("backend.Models.Movimento", "Movimento")
                        .WithOne("Retrabalho")
                        .HasForeignKey("backend.Models.Retrabalho", "IdMovimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retrabalhos_movimentos_idmovimento");

                    b.HasOne("backend.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaRejeicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retrabalhos_maquinas_maquinarejeicao");

                    b.Navigation("Maquina");

                    b.Navigation("Movimento");
                });

            modelBuilder.Entity("backend.Models.Utilizador", b =>
                {
                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("Utilizadores")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_utilizadores_cargos_cargoid");

                    b.HasOne("backend.Models.Nivel", "Nivel")
                        .WithMany("Utilizadores")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_utilizadores_niveis_nivelid");

                    b.Navigation("Cargo");

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("backend.Models.Artigo", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("HistoricoCustos");

                    b.Navigation("PropriedadesPDM");

                    b.Navigation("Rececoes");
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("backend.Models.DocumentoTecnico", b =>
                {
                    b.Navigation("Assinaturas");
                });

            modelBuilder.Entity("backend.Models.Familia", b =>
                {
                    b.Navigation("DiversosLista");
                });

            modelBuilder.Entity("backend.Models.Fornecedor", b =>
                {
                    b.Navigation("Classificacoes");
                });

            modelBuilder.Entity("backend.Models.Maquina", b =>
                {
                    b.Navigation("Artigos");
                });

            modelBuilder.Entity("backend.Models.Movimento", b =>
                {
                    b.Navigation("NaoConforme");

                    b.Navigation("Retrabalho");
                });

            modelBuilder.Entity("backend.Models.Nivel", b =>
                {
                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("backend.Models.RececaoInspecao", b =>
                {
                    b.Navigation("Justificacoes");
                });

            modelBuilder.Entity("backend.Models.Servico", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("backend.Models.TipoMovimento", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("backend.Models.Utilizador", b =>
                {
                    b.Navigation("Assinaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
