// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Artigo", b =>
                {
                    b.Property<string>("ArtigoCodigo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("DiversosId")
                        .HasColumnType("integer");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("integer");

                    b.Property<string>("MaquinaCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ArtigoCodigo");

                    b.HasIndex("DiversosId");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("MaquinaCodigo");

                    b.ToTable("Artigos");
                });

            modelBuilder.Entity("backend.Models.ArtigoCusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtigoCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("CustoPintura")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PraMatprim")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecoEnergia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PruMaquina")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrwiMaoobra")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ArtigoCodigo");

                    b.ToTable("ArtigosCusto");
                });

            modelBuilder.Entity("backend.Models.AssinaturaDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssinaturaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("DataAssinatura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartamentoAssinatura")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("integer");

                    b.Property<string>("UtilizadorCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("AssinaturaHash")
                        .IsUnique();

                    b.HasIndex("DocumentoId");

                    b.HasIndex("UtilizadorCodigo");

                    b.ToTable("AssinaturasDocumento");
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("backend.Models.CatalogoDefeito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("CatalogosDefeito");
                });

            modelBuilder.Entity("backend.Models.Diversos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("DiversosLista");
                });

            modelBuilder.Entity("backend.Models.DocumentoTecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtigoCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CaminhoFicheiro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsOficial")
                        .HasColumnType("boolean");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtigoCodigo");

                    b.HasIndex("CaminhoFicheiro")
                        .IsUnique();

                    b.ToTable("DocumentosTecnicos");
                });

            modelBuilder.Entity("backend.Models.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ParametrosInspecao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("backend.Models.Fornecedor", b =>
                {
                    b.Property<string>("FornecedorCodigo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Morada")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("FornecedorCodigo");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("backend.Models.FornecedorClassificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoFiscal")
                        .HasColumnType("integer");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FornecedorCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorCodigo", "AnoFiscal")
                        .IsUnique();

                    b.ToTable("FornecedoresClassificacao");
                });

            modelBuilder.Entity("backend.Models.JustificacaoNOK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefeitoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("QtdAfetada")
                        .HasColumnType("numeric");

                    b.Property<int>("RececaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefeitoId");

                    b.HasIndex("RececaoId");

                    b.ToTable("JustificacoesNOK");
                });

            modelBuilder.Entity("backend.Models.Maquina", b =>
                {
                    b.Property<string>("MaquinaCodigo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecoEnergia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecoMaoObra")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecoUsinagem")
                        .HasColumnType("numeric");

                    b.Property<int?>("Setor")
                        .HasColumnType("integer");

                    b.HasKey("MaquinaCodigo");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("backend.Models.Movimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtigoCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefeitoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Descontar")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MaquinaCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<int?>("ServicoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoMovimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("UtilizadorCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtigoCodigo");

                    b.HasIndex("DefeitoId");

                    b.HasIndex("MaquinaCodigo");

                    b.HasIndex("ServicoId");

                    b.HasIndex("TipoMovimentoId");

                    b.HasIndex("UtilizadorCodigo");

                    b.ToTable("Movimentos");
                });

            modelBuilder.Entity("backend.Models.NaoConforme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdMovimento")
                        .HasColumnType("integer");

                    b.Property<decimal>("QtdSage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdMovimento")
                        .IsUnique();

                    b.ToTable("NaoConformes");
                });

            modelBuilder.Entity("backend.Models.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("Niveis");
                });

            modelBuilder.Entity("backend.Models.RececaoInspecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtigoCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("CustoUnitarioMomento")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataRececao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisaoFinal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Fatura")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FornecedorCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Linha")
                        .HasColumnType("integer");

                    b.Property<decimal>("QtdTotalRecebida")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<string>("SagePedidoId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UtilizadorCodigo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtigoCodigo");

                    b.HasIndex("FornecedorCodigo");

                    b.HasIndex("UtilizadorCodigo");

                    b.HasIndex("SagePedidoId", "Linha")
                        .IsUnique();

                    b.ToTable("RececoesInspecao");
                });

            modelBuilder.Entity("backend.Models.Retrabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcaoExecutar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("CustoNc")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CustoRejeicao")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CustoRetrabalho")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataRetrabalho")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdMovimento")
                        .HasColumnType("integer");

                    b.Property<string>("MaquinaRejeicao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SetorIdentificado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("TempoMinutos")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdMovimento")
                        .IsUnique();

                    b.HasIndex("MaquinaRejeicao");

                    b.ToTable("Retrabalhos");
                });

            modelBuilder.Entity("backend.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CustoDecapar")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("backend.Models.TipoMovimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("TiposMovimento");
                });

            modelBuilder.Entity("backend.Models.Utilizador", b =>
                {
                    b.Property<string>("UtilizadorCodigo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("CargoId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("UtilizadorCodigo");

                    b.HasIndex("CargoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NivelId");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("backend.Models.Artigo", b =>
                {
                    b.HasOne("backend.Models.Diversos", "Diversos")
                        .WithMany("Artigos")
                        .HasForeignKey("DiversosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Familia", "Familia")
                        .WithMany()
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Maquina", "Maquina")
                        .WithMany("Artigos")
                        .HasForeignKey("MaquinaCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diversos");

                    b.Navigation("Familia");

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("backend.Models.ArtigoCusto", b =>
                {
                    b.HasOne("backend.Models.Artigo", "Artigo")
                        .WithMany("HistoricoCustos")
                        .HasForeignKey("ArtigoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");
                });

            modelBuilder.Entity("backend.Models.AssinaturaDocumento", b =>
                {
                    b.HasOne("backend.Models.DocumentoTecnico", "Documento")
                        .WithMany("Assinaturas")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Utilizador", "Utilizador")
                        .WithMany("Assinaturas")
                        .HasForeignKey("UtilizadorCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("backend.Models.Diversos", b =>
                {
                    b.HasOne("backend.Models.Familia", null)
                        .WithMany("DiversosLista")
                        .HasForeignKey("FamiliaId");
                });

            modelBuilder.Entity("backend.Models.DocumentoTecnico", b =>
                {
                    b.HasOne("backend.Models.Artigo", "Artigo")
                        .WithMany("Documentos")
                        .HasForeignKey("ArtigoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");
                });

            modelBuilder.Entity("backend.Models.FornecedorClassificacao", b =>
                {
                    b.HasOne("backend.Models.Fornecedor", "Fornecedor")
                        .WithMany("Classificacoes")
                        .HasForeignKey("FornecedorCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("backend.Models.JustificacaoNOK", b =>
                {
                    b.HasOne("backend.Models.CatalogoDefeito", "Defeito")
                        .WithMany()
                        .HasForeignKey("DefeitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.RececaoInspecao", "Rececao")
                        .WithMany("Justificacoes")
                        .HasForeignKey("RececaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defeito");

                    b.Navigation("Rececao");
                });

            modelBuilder.Entity("backend.Models.Movimento", b =>
                {
                    b.HasOne("backend.Models.Artigo", "Artigo")
                        .WithMany()
                        .HasForeignKey("ArtigoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.CatalogoDefeito", "Defeito")
                        .WithMany()
                        .HasForeignKey("DefeitoId");

                    b.HasOne("backend.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Servico", "Servico")
                        .WithMany("Movimentos")
                        .HasForeignKey("ServicoId");

                    b.HasOne("backend.Models.TipoMovimento", "Tipo")
                        .WithMany("Movimentos")
                        .HasForeignKey("TipoMovimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");

                    b.Navigation("Defeito");

                    b.Navigation("Maquina");

                    b.Navigation("Servico");

                    b.Navigation("Tipo");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("backend.Models.NaoConforme", b =>
                {
                    b.HasOne("backend.Models.Movimento", "Movimento")
                        .WithOne("NaoConforme")
                        .HasForeignKey("backend.Models.NaoConforme", "IdMovimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimento");
                });

            modelBuilder.Entity("backend.Models.RececaoInspecao", b =>
                {
                    b.HasOne("backend.Models.Artigo", "Artigo")
                        .WithMany()
                        .HasForeignKey("ArtigoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");

                    b.Navigation("Fornecedor");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("backend.Models.Retrabalho", b =>
                {
                    b.HasOne("backend.Models.Movimento", "Movimento")
                        .WithOne("Retrabalho")
                        .HasForeignKey("backend.Models.Retrabalho", "IdMovimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaRejeicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maquina");

                    b.Navigation("Movimento");
                });

            modelBuilder.Entity("backend.Models.Utilizador", b =>
                {
                    b.HasOne("backend.Models.Cargo", "Cargo")
                        .WithMany("Utilizadores")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Nivel", "Nivel")
                        .WithMany("Utilizadores")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("backend.Models.Artigo", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("HistoricoCustos");
                });

            modelBuilder.Entity("backend.Models.Cargo", b =>
                {
                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("backend.Models.Diversos", b =>
                {
                    b.Navigation("Artigos");
                });

            modelBuilder.Entity("backend.Models.DocumentoTecnico", b =>
                {
                    b.Navigation("Assinaturas");
                });

            modelBuilder.Entity("backend.Models.Familia", b =>
                {
                    b.Navigation("DiversosLista");
                });

            modelBuilder.Entity("backend.Models.Fornecedor", b =>
                {
                    b.Navigation("Classificacoes");
                });

            modelBuilder.Entity("backend.Models.Maquina", b =>
                {
                    b.Navigation("Artigos");
                });

            modelBuilder.Entity("backend.Models.Movimento", b =>
                {
                    b.Navigation("NaoConforme");

                    b.Navigation("Retrabalho");
                });

            modelBuilder.Entity("backend.Models.Nivel", b =>
                {
                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("backend.Models.RececaoInspecao", b =>
                {
                    b.Navigation("Justificacoes");
                });

            modelBuilder.Entity("backend.Models.Servico", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("backend.Models.TipoMovimento", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("backend.Models.Utilizador", b =>
                {
                    b.Navigation("Assinaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
